version: "3"

services: 
  webgoat: 
    image: webgoat/webgoat-8.0:latest
    container_name: webgoat
    environment:
      - discovery.type=single-node
    ports: 
      - 81:8080
  
  dvwa:
    tty: true
    image: rwils83/dvwa_with_curl:latest
    container_name: dvwa
    environment:
      - discovery.type=single-node
    ports:
      - 80:80
  
  juiceshop:
    image: bkimminich/juice-shop:latest
    container_name: juiceshop
    environment:
      - discovery.type=single-node
    ports:
      - 82:3000
  phpldapadmin:
    image: vulnerables/phpldapadmin-remote-dump:latest
    container_name: phpldapadmin
    environment:
      - discovery.type=single-node
    ports:
      - 83:80
  database:
      container_name: database
      image: webpwnized/mutillidae:database
      build:
          context: ./database
          dockerfile: Dockerfile
      networks:
        - datanet

  database_admin:
    container_name: database_admin
    depends_on:
      - database
    image: webpwnized/mutillidae:database_admin
    build:
        context: ./database_admin
        dockerfile: Dockerfile
    ports:
      - 84:80
    networks:
      - datanet

  www:
    container_name: www
    depends_on:
      - database
      - directory
    image: webpwnized/mutillidae:www
    build:
        context: ./www
        dockerfile: Dockerfile
    ports:
      - 85:80
      - 8443:443
    networks:
      - datanet
      - ldapnet

  directory:
    container_name: directory
    image: webpwnized/mutillidae:ldap
    build:
        context: ./ldap
        dockerfile: Dockerfile
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - ldapnet

  directory_admin:
    container_name: directory_admin
    depends_on:
      - directory
    image: webpwnized/mutillidae:ldap_admin
    build:
        context: ./ldap_admin
        dockerfile: Dockerfile
    ports:
      - 86:80
    networks:
      - ldapnet

  volumes:
    ldap_data:
    ldap_config:

# Create network segments for the containers to use
  networks:
    datanet:
    ldapnet: