version: "3.7"

services: 
  webgoat: 
    image: webgoat/webgoat-8.0:latest
    container_name: webgoat
    environment:
      - discovery.type=single-node
    ports: 
      - 81:8080
  
  dvwa:
    tty: true
    image: rwils83/dvwa_with_curl:latest
    container_name: dvwa
    environment:
      - discovery.type=single-node
    ports:
      - 80:80
  
  juiceshop:
    image: bkimminich/juice-shop:latest
    container_name: juiceshop
    environment:
      - discovery.type=single-node
    ports:
      - 82:3000
  phpldapadmin:
    image: vulnerables/phpldapadmin-remote-dump:latest
    container_name: phpldapadmin
    environment:
      - discovery.type=single-node
    ports:
      - 83:80
  vAmPI:
    imgage: erev0s/vampi
    container_name: vampi
    environment:
      - discovery.type=single-node
    ports:
      - 84:5001
  vAmPISecure:
    image: erev0s/vampi
    container_name: vampi_secure
    environment: 
      -discovery.type=single-node
    ports:
      - 85:5000
