version: "3.7"

services: 
  webgoat: 
    image: webgoat/webgoat-8.0:latest
    container_name: webgoat
    environment:
      - discovery.type=single-node
    ports: 
      - 81:8080
  
  dvwa:
    tty: true
    image: rwils83/dvwa_with_curl:latest
    container_name: dvwa
    environment:
      - discovery.type=single-node
    ports:
      - 80:80
  
  juiceshop:
    image: bkimminich/juice-shop:latest
    container_name: juiceshop
    environment:
      - discovery.type=single-node
    ports:
      - 82:3000
  phpldapadmin:
    image: vulnerables/phpldapadmin-remote-dump:latest
    container_name: phpldapadmin
    environment:
      - discovery.type=single-node
    ports:
      - 83:80
  vampi:
    image: erev0s/vampi
    environment:
      - vulnerable=1
    ports:
      - 84:5000

  vampi_secure:
    image: erev0s/vampi
    environment:
      - vulnerable=0
    ports:
      - 85:5000
